### ISSUE TITLE
Error caused by ChamferDistance

### ISSUE THREAD

**Issue by CHMimilanlan** [AlvinYH/FreeCloth#1]
After I ran `python main.py --mode=test`, I got following error:  

File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 399, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/data/xch/Avatar/3D/FreeCloth/lib/freecloth_model.py", line 332, in test_step
    m2s, s2m, loss_nml = compute_cd_nml(pred_pc, pred_nml, data['clothed_pc'], data['clothed_nml'])
  File "/data/xch/Avatar/3D/FreeCloth/lib/model/losses.py", line 87, in compute_cd_nml
    _, s2m, idx_closest_gt, _ = chamfer_dist(output, target) #idx1: [#pred points]
  File "/data/xch/Avatar/3D/FreeCloth/lib/model/losses.py", line 61, in chamfer_dist
    model2scan, scan2model, idx1, idx2 = cdist(output, target)
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/site-packages/torch/_tensor.py", line 723, in __iter__
    raise TypeError('iteration over a 0-d tensor')

It was caused by ChamferDistance. I checked the `forward call` of ChamferDistance, it returns one varible which is `chamfer_forward`.
![image](https://github.com/user-attachments/assets/d5da5ac6-cf77-471c-b1e2-81fb8faa999b)

However, you make 4 variable to unpack
`    model2scan, scan2model, idx1, idx2 = cdist(output, target)`
I guess it was caused by the version of ChamferDistance. Could you give me a solution to solve this?

I will be grateful for your timely response!

**Comment by CHMimilanlan** [comment]
I thought it might because of I install wrong version of ChamferDist, could you please provide your version of ChamferDist?

**Comment by CHMimilanlan** [comment]
Never mind, I have solved.

**Comment by HandSomeWay** [comment]
Hi @CHMimilanlan.

I’m reproducing the same setup and encountered the same error.  
Could you please share more details about how you fixed it (e.g., code changes or dependency versions)?

That would be very helpful. Thanks in advance!
